# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: PointNav-v1
split: train
data_path: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256